### ISSUE TITLE
Manage / Cancel Subscription = Server Error?!?!?!

### ISSUE THREAD

**Issue by NeoRey73** [jbwhaley/LinkLocker-issues#6] opened 2017-11-17 07:48 UTC
Like I said in the title... I want to cancel my subscription before the three day trial ends. The past three days I get a Server Error?

![screen shot 2017-11-17 at 08 47 44](https://user-images.githubusercontent.com/26891752/32936374-511b4a84-cb74-11e7-8975-300cdb77e48f.png)

**Comment by jbwhaley** [comment] 2017-11-17 08:43
This seems to be caused by a simple bug affecting your account due to some kind of edge case. Don't worry at all, we'll get it straightened out. 

I've pushed a fix (hopefully) to the code which seems to be causing the issue. Please try to cancel again, and let me know if you still have trouble doing so.

In the end, rest assured that I will help you sort this out.

**Comment by NeoRey73** [comment] 2017-11-17 08:46
Thank you. It's not working yet, when I follow this link https://linklocker.co/manage-subscription I get the Server Error page

**Comment by jbwhaley** [comment] 2017-11-17 08:50
OK, sorry that tweak I just made didn't fix it. So that we can keep your details private, will you go to the [contact page](https://linklocker.co/contact) and send me the email address you use to log in? And if possible, the subscription ID that was sent to you in your receipt when you signed up?

**Comment by NeoRey73** [comment] 2017-11-17 09:01
Thanks. I can't find the subscription ID but filled out the contact form.

**Comment by jbwhaley** [comment] 2017-11-17 09:03
OK, thanks. Let me try to track down what the problem might be, and I'll contact you (probably by email) when I've sorted it out.

**Comment by jbwhaley** [comment] 2017-11-17 09:28
OK, I do think it has been fixed now. Please try again and let me know if you have any further trouble.

**Comment by NeoRey73** [comment] 2017-11-17 11:32
I think it is working. Now it says "Your subscription will renew on Nov. 18, 2017." and I can cancel. Well done!

I cancelled because I thought it was a multi platform bookmark sync tool but it is more similar to Pocket.

**Comment by jbwhaley** [comment] 2017-11-17 15:29
I would argue that LinkLocker provides a means of taking your bookmarks with you across platforms, in that they are accessible everywhere via the Web--so it meets the same need as a sync service, but with additional features. :-)

OK, thanks for letting me know you were able to cancel. I will now close this issue.

**Closed as completed** 2017-11-17 15:29 UTC
